### ISSUE TITLE
add support to generate .gitignore based on language

### ISSUE THREAD

**Issue by Grisolfi** [paulosell/auto-project-python#1]
Could be awesome if it detects used languages and suggests the addition of appropriated .gitignore file.

**Comment by paulosell** [comment]
Added the -n and -i arguments.

-n Project name
-i languages used in the project (optional)

.gitignore files are based on gitignore.io templates (check their [repo](https://github.com/toptal/gitignore/tree/master/templates) to see available templates)

usage example:

```
create-project -n <nome_do_projeto> -i [-i <lang1,lang2...langN>]
```
